version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=${{ DATABASE_URL }}
    volumes:
      - data:/app/instance

volumes:
  data:
